/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;
import Entidades.Incidente;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Proyector
 */
public class FrameRegistrar extends javax.swing.JFrame {

private FrameVisualizar padre; 
private Incidente incidente;
private boolean prioridad;
private boolean checkBoxPrioridadSelected;
 private boolean estoyEditando = false;
 public static List<Incidente> listaDeIncidentes;
  
    /**
     * Creates new form RegistrarIncidente
     */
    public FrameRegistrar() {
        initComponents();
    }
    public FrameRegistrar(FrameVisualizar padre){
      initComponents();
      this.padre = padre;
     
      
     this.checkBoxPrioridadSelected = false;
  this.prioridad = false;
        

      }

 

    
    
    private void CheckBoxPrioridadActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        // Toggle the priority status when the checkbox is clicked
        prioridad = checkBoxPrioridad.isSelected();
    }  
    
    
    
    
                                       
private void salir(){
      padre.setVisible(true);
      this.dispose();
    }


 




 public FrameRegistrar(FrameVisualizar padre, Incidente incidente) {
        initComponents();
        this.padre = padre;
        this.incidente = incidente;
        this.estoyEditando = true;
 
        this.txtTipo.setText(incidente.getTipo());
        this.txtHora.setText(incidente.getHora());
        this.txtFecha.setText(incidente.getFecha());
        this.txtDescripcion.setText(incidente.getDescripcion());
        this.txtTestigo.setText(incidente.getTestigo());

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTestigo = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        checkBoxPrioridad = new javax.swing.JCheckBox();
        lblRegistrar = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTestigo.setBorder(null);
        jPanel1.add(txtTestigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 160, 30));

        txtTipo.setBorder(null);
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 170, 20));

        txtFecha.setBorder(null);
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 170, 20));

        txtHora.setBorder(null);
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 170, 20));

        txtDescripcion.setBorder(null);
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 270, 250));

        checkBoxPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPrioridadActionPerformed(evt);
            }
        });
        jPanel1.add(checkBoxPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 20, 20));

        lblRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registrarr.png"))); // NOI18N
        lblRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, -1, -1));

        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });
        jPanel1.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PRIORI.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:}
        salir();
        
    }//GEN-LAST:event_lblSalirMouseClicked

    
    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        // TODO add your handling code here:
        if (txtTipo.getText().isEmpty() || txtFecha.getText().isEmpty() 
                || txtHora.getText().isEmpty() || txtDescripcion
                        .getText().isEmpty() 
                || txtTestigo.getText().isEmpty()) {
        // Muestra un cuadro de diálogo de error
            JOptionPane.showMessageDialog(this
                    , "Por favor, llene todos los campos", "Error"
                    , JOptionPane.ERROR_MESSAGE);
        return;  // Sale del método si hay campos vacíos
        }
   //  padre.updateIncidentList();
      if (incidente != null) {
       
        incidente.setTipo(txtTipo.getText());
        incidente.setFecha(txtFecha.getText());
        incidente.setHora(txtHora.getText());
        incidente.setDescripcion(txtDescripcion.getText());
       incidente.setTestigo(txtTestigo.getText());
        this.padre.actualizarI(incidente);
    } else {
       
        String tipo = txtTipo.getText();
  String fecha = txtFecha.getText();
   String hora = txtHora.getText();
   String descripcion = txtDescripcion.getText();
   String testigo = txtTestigo.getText();//-
     
        Incidente nuevoIncidente = new Incidente(fecha, tipo, descripcion, hora,testigo);
        nuevoIncidente.setTipo(txtTipo.getText()); 
        nuevoIncidente.setFecha(txtFecha.getText());
        nuevoIncidente.setDescripcion(txtDescripcion.getText());
        nuevoIncidente.setHora(txtHora.getText());
        nuevoIncidente.setTestigo(txtTestigo.getText());
        // Llama a un método en FrameEstudiantes para agregar el nuevo estudiante al modelo del JList.
        this.padre.agregarI(nuevoIncidente);
    
      
      
    
      
      }
    
      
      
      
      
    // Mostrar FrameEstudiantes nuevamente y cerrar FrameEstudiante
    this.padre.setVisible(true);
    this.dispose();
    
    
    
    
       
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void checkBoxPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPrioridadActionPerformed
        // TODO add your handling code here:
        
          if (checkBoxPrioridad.isSelected()) {
        // If priority is selected, move the incident to the front
        padre.moveIncidentToFront(incidente);
    } else {
        // If priority is not selected, refresh the incident list in its original order
        padre.updateIncidentList();
    }
        
    }//GEN-LAST:event_checkBoxPrioridadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtTestigo;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
